///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : rportvcs_brakepedal.h
/// SOFTWARE COMPONENT NAME           : RPortVCS_BrakePedal
/// GENERATED DATE                    : 2025-08-30 10:53:28
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_AA_GEN_SOFTWARE_COMPONENT_RPORT_PREVENTROLLBACK_AA_RPORTVCS_BRAKEPEDAL_H
#define PARA_AA_GEN_SOFTWARE_COMPONENT_RPORT_PREVENTROLLBACK_AA_RPORTVCS_BRAKEPEDAL_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "eevp/simulation/vcs_brakepedal_proxy.h"
 
#include "ara/log/logger.h"
 
#include <mutex>
#include <thread>
 
namespace preventrollback
{
namespace aa
{
namespace port
{
 
class RPortVCS_BrakePedal
{
public:
    /// @brief Constructor
    RPortVCS_BrakePedal();
    
    /// @brief Destructor
    ~RPortVCS_BrakePedal();
    
    /// @brief Start port
    void Start();
    
    /// @brief Terminate port
    void Terminate();

    /// @brief Request with Response method using by software component, notifyBrakeStatus
    void RequestnotifyBrakeStatus();
     
    /// @brief Regist callback from software component
    void RegistResponseHandlernotifyBrakeStatus(std::function<void(const eevp::simulation::proxy::methods::notifyBrakeStatus::Output&)> handler);
    
    /// @brief Request with Response method using by software component, notifyBrakeSwitch
    void RequestnotifyBrakeSwitch();
     
    /// @brief Regist callback from software component
    void RegistResponseHandlernotifyBrakeSwitch(std::function<void(const eevp::simulation::proxy::methods::notifyBrakeSwitch::Output&)> handler);
    
private:
    /// @brief Callback for find service
    void Find(ara::com::ServiceHandleContainer<eevp::simulation::proxy::VCS_BrakePedalProxy::HandleType> handles,
              ara::com::FindServiceHandle findHandle);

private:
    /// @brief Logger for this port
    ara::log::Logger& m_logger;
    
    /// @brief Flag of port status
    bool m_running;
    
    /// @brief Flag of find service status
    bool m_found;
    
    /// @brief Mutex for this port
    std::mutex m_mutex; 
    
    /// @brief AUTOSAR Port Interface
    std::unique_ptr<eevp::simulation::proxy::VCS_BrakePedalProxy> m_interface;
    
    /// @brief Find service handle
    std::unique_ptr<ara::com::FindServiceHandle> m_findHandle;

    /// @brief Callback from software component, notifyBrakeStatus
    std::function<void(const eevp::simulation::proxy::methods::notifyBrakeStatus::Output&)> m_respondernotifyBrakeStatus;
    
    /// @brief Callback from software component, notifyBrakeSwitch
    std::function<void(const eevp::simulation::proxy::methods::notifyBrakeSwitch::Output&)> m_respondernotifyBrakeSwitch;
};
 
} /// namespace port
} /// namespace aa
} /// namespace preventrollback
 
#endif /// PARA_AA_GEN_SOFTWARE_COMPONENT_RPORT_PREVENTROLLBACK_AA_RPORTVCS_BRAKEPEDAL_H