///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : rport_vehicleinfo.cpp
/// SOFTWARE COMPONENT NAME           : RPort_VehicleInfo
/// GENERATED DATE                    : 2025-08-14 16:16:30
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "intelligentwiper/aa/port/rport_vehicleinfo.h"
 
namespace intelligentwiper
{
namespace aa
{
namespace port
{
 
RPort_VehicleInfo::RPort_VehicleInfo()
    : m_logger(ara::log::CreateLogger("INTW", "PORT", ara::log::LogLevel::kInfo))
    , m_running{false}
    , m_found{false}
    , m_receiversoaVehicleInfo{nullptr}
{
}
 
RPort_VehicleInfo::~RPort_VehicleInfo()
{
}
 
void RPort_VehicleInfo::Start()
{
    m_logger.LogInfo() << "RPort_VehicleInfo::Start";
    
    // regist callback
    ara::core::InstanceSpecifier specifier{"IntelligentWiper/AA/RPort_VehicleInfo"};
    auto handler = [this](ara::com::ServiceHandleContainer<eevp::control::proxy::SoaVehicleInfoProxy::HandleType> handles,
                          ara::com::FindServiceHandle findHandle) {
        this->Find(handles, findHandle);
    };
    
    // find service
    auto find = eevp::control::proxy::SoaVehicleInfoProxy::StartFindService(handler, specifier);
    if (find.HasValue())
    {
        m_logger.LogInfo() << "RPort_VehicleInfo::Start::StartFindService";
    }
    else
    {
        m_logger.LogError() << "RPort_VehicleInfo::Start::StartFindService::" << find.Error().Message();
    }
    
    // run port
    m_running = true;
}
 
void RPort_VehicleInfo::Terminate()
{
    m_logger.LogInfo() << "RPort_VehicleInfo::Terminate";
    
    // stop port
    m_running = false;
    
    // clear service proxy
    if (m_interface)
    {
        StopSubscribesoaVehicleInfo();
        
        // stop find service
        m_interface->StopFindService(*m_findHandle);
        m_found = false;
        
        m_logger.LogInfo() << "RPort_VehicleInfo::Terminate::StopFindService";
    }
}
 
void RPort_VehicleInfo::Find(ara::com::ServiceHandleContainer<eevp::control::proxy::SoaVehicleInfoProxy::HandleType> handles, ara::com::FindServiceHandle findHandle)
{
    // check finding handles
    if (handles.empty())
    {
        m_logger.LogInfo() << "RPort_VehicleInfo::Find::Service Instances not found";
        return;
    }
    else
    {
        for (auto& handle : handles)
        {
            m_logger.LogInfo() << "RPort_VehicleInfo::Find::Searched Instance::ServiceId =" << 
                                     handle.GetServiceHandle().serviceId << 
                                     ", InstanceId =" << 
                                     handle.GetServiceHandle().instanceId;
        }
    }
    
    // create proxy
    if (m_interface)
    {
        m_logger.LogInfo() << "RPort_VehicleInfo::Find::Proxy is already running";
    }
    else
    {
        m_logger.LogInfo() << "RPort_VehicleInfo::Find::Using Instance::ServiceId =" << 
                                 handles[0].GetServiceHandle().serviceId << 
                                 ", InstanceId =" << 
                                 handles[0].GetServiceHandle().instanceId;
        m_interface = std::make_unique<eevp::control::proxy::SoaVehicleInfoProxy>(handles[0]);
        m_findHandle = std::make_unique<ara::com::FindServiceHandle>(findHandle);
        m_found = true;
        
        // subscribe field notifications
        SubscribesoaVehicleInfo();
    }
}
 
void RPort_VehicleInfo::SubscribesoaVehicleInfo()
{
    if (m_found)
    {
        // regist receiver handler
        // if you want to enable it, please uncomment below code
        RegistReceiversoaVehicleInfo();
        
        // request subscribe
        auto subscribe = m_interface->soaVehicleInfo.Subscribe(1);
        if (subscribe.HasValue())
        {
            m_logger.LogInfo() << "RPort_VehicleInfo::SubscribesoaVehicleInfo::Subscribed";
        }
        else
        {
            m_logger.LogError() << "RPort_VehicleInfo::SubscribesoaVehicleInfo::" << subscribe.Error().Message();
        }
    }
}
 
void RPort_VehicleInfo::StopSubscribesoaVehicleInfo()
{
    if (m_found)
    {
        // request stop subscribe
        m_interface->soaVehicleInfo.Unsubscribe();
        m_logger.LogInfo() << "RPort_VehicleInfo::StopSubscribesoaVehicleInfo::Unsubscribed";
    }
}
 
void RPort_VehicleInfo::RegistReceiversoaVehicleInfo()
{
    if (m_found)
    {
        // set callback
        auto receiver = [this]() -> void {
            return ReceiveFieldsoaVehicleInfoTriggered();
        };
        
        // regist callback
        auto callback = m_interface->soaVehicleInfo.SetReceiveHandler(receiver);
        if (callback.HasValue())
        {
            m_logger.LogInfo() << "RPort_VehicleInfo::RegistReceiversoaVehicleInfo::SetReceiveHandler";
        }
        else
        {
            m_logger.LogError() << "RPort_VehicleInfo::RegistReceiversoaVehicleInfo::SetReceiveHandler::" << callback.Error().Message();
        }
    }
}
 
void RPort_VehicleInfo::ReceiveFieldsoaVehicleInfoTriggered()
{
    if (m_found)
    {
        std::lock_guard<std::mutex> lock(m_mutex);
        
        if (m_interface->soaVehicleInfo.GetSubscriptionState() == ara::com::SubscriptionState::kSubscribed)
        {
            auto recv = std::make_unique<ara::core::Result<size_t>>(m_interface->soaVehicleInfo.GetNewSamples([&](auto samplePtr) {
                RPort_VehicleInfo::ReadValuesoaVehicleInfo(std::move(samplePtr));
            }));
            if (recv->HasValue())
            {
                m_logger.LogInfo() << "RPort_VehicleInfo::ReceiveFieldsoaVehicleInfo::GetNewSamples::" << recv->Value();
            }
            else
            {
                m_logger.LogError() << "RPort_VehicleInfo::ReceiveFieldsoaVehicleInfo::GetNewSamples::" << recv->Error().Message();
            }
        }
    }
}
 
void RPort_VehicleInfo::ReceiveFieldsoaVehicleInfoCyclic()
{
    while (m_running)
    {
        std::lock_guard<std::mutex> lock(m_mutex);
        
        if (m_found)
        {
            if (m_interface->soaVehicleInfo.GetSubscriptionState() == ara::com::SubscriptionState::kSubscribed)
            {
                auto recv = std::make_unique<ara::core::Result<size_t>>(m_interface->soaVehicleInfo.GetNewSamples([&](auto samplePtr) {
                    RPort_VehicleInfo::ReadValuesoaVehicleInfo(std::move(samplePtr));
                }));
                if (recv->HasValue())
                {
                    m_logger.LogInfo() << "RPort_VehicleInfo::ReceiveFieldsoaVehicleInfo::GetNewSamples::" << recv->Value();
                }
                else
                {
                    m_logger.LogError() << "RPort_VehicleInfo::ReceiveFieldsoaVehicleInfo::GetNewSamples::" << recv->Error().Message();
                }
            }
        }
        std::this_thread::sleep_for(std::chrono::seconds(1));
    }
}
 
void RPort_VehicleInfo::ReadValuesoaVehicleInfo(ara::com::SamplePtr<eevp::control::proxy::fields::soaVehicleInfo::FieldType const> samplePtr)
{
    auto value = *samplePtr.Get();
    if (m_receiversoaVehicleInfo)
    {
        m_receiversoaVehicleInfo(value);
    }
}
 
void RPort_VehicleInfo::GetsoaVehicleInfo()
{
    if (m_found)
    {
        auto request = m_interface->soaVehicleInfo.Get();
        request.wait();
        auto response = request.GetResult();
        if (response.HasValue())
        {
            m_logger.LogVerbose() << "RPort_VehicleInfo::GetsoaVehicleInfo::Responded";
            
            auto result = response.Value();
            if (m_receiversoaVehicleInfo)
            {
                m_receiversoaVehicleInfo(result);
            }
        }
        else
        {
            m_logger.LogError() << "RPort_VehicleInfo::GetsoaVehicleInfo::" << response.Error().Message();
        }
    }
}
 
void RPort_VehicleInfo::RegistFieldHandlersoaVehicleInfo(std::function<void(const eevp::control::proxy::fields::soaVehicleInfo::FieldType&)> handler)
{
    m_receiversoaVehicleInfo = handler;
}
 
} /// namespace port
} /// namespace aa
} /// namespace intelligentwiper
 
/// EOF