///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, ARA::COM Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : impl_type_inputdata.h
/// IMPLEMENTATION DATA TYPE NAME     : InputData
/// GENERATED DATE                    : 2024-09-04 11:02:58
///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// CAUTION!! AUTOMATICALLY GENERATED FILE - DO NOT EDIT                                                   
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_ARA_COM_GEN_CPP_IMPL_TYPE_INPUTDATA_H
#define PARA_ARA_COM_GEN_CPP_IMPL_TYPE_INPUTDATA_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// @uptrace{SWS_CM_00402}
#include <cstdint>
#include <ara/core/structure.h>
/// @uptrace{SWS_CM_10375}
namespace bms
{
namespace input
{
struct InputData
{
    std::uint32_t InterfaceIDforDbg;
    std::uint32_t DataSerialNumber;
    std::uint32_t VehicleUniqueSnr;
    std::uint32_t EMS_BatteryAvgTemperature;
    std::uint32_t EMS_ChargerOutputVolt;
    std::uint32_t EMS_ChargerOutputCurr;
    std::uint32_t EMS_ReturnCode;
    std::uint32_t EMS_ConnectionStatus;
    std::uint32_t EMS_TargetVolt;
    std::uint32_t EMS_TargetCurr;
    std::uint32_t EMS_RemainHour;
    std::uint32_t EMS_RemainMin;
    std::uint32_t EMS_HVBattSOC;
    std::uint32_t EMS_HVBattSOE;
    std::uint32_t EMS_HVBattSOH;
    std::uint32_t EMS_BattVolt;
    std::uint32_t EMS_BattCurr;
    std::uint32_t EMS_Obc_dcVolt;
    std::uint32_t EMS_Obc_dcCurr;
    std::uint32_t EMS_Avn_ChargeCurrSetSts;
    std::uint32_t EMS_HVBatt_MainRlyCloseReq;
    std::uint32_t EMS_HVBatt_preChrgRlyStatus;
    std::uint32_t EMS_HVBatt_posRlyStatus;
    std::uint32_t EMS_HVBatt_negRlyStatus;
    std::uint32_t EMS_Avn_DcChargingTargetSetSts;
    std::uint32_t EMS_Avn_AcChargingTargetSetSts;
    PARA_STRUCTURE(InputData, InterfaceIDforDbg, DataSerialNumber, VehicleUniqueSnr, EMS_BatteryAvgTemperature, EMS_ChargerOutputVolt, EMS_ChargerOutputCurr, EMS_ReturnCode, EMS_ConnectionStatus, EMS_TargetVolt, EMS_TargetCurr, EMS_RemainHour, EMS_RemainMin, EMS_HVBattSOC, EMS_HVBattSOE, EMS_HVBattSOH, EMS_BattVolt, EMS_BattCurr, EMS_Obc_dcVolt, EMS_Obc_dcCurr, EMS_Avn_ChargeCurrSetSts, EMS_HVBatt_MainRlyCloseReq, EMS_HVBatt_preChrgRlyStatus, EMS_HVBatt_posRlyStatus, EMS_HVBatt_negRlyStatus, EMS_Avn_DcChargingTargetSetSts, EMS_Avn_AcChargingTargetSetSts);
};
} /// namespace input
} /// namespace bms
#endif /// PARA_ARA_COM_GEN_CPP_IMPL_TYPE_INPUTDATA_H