///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : pport_snsr_heartbeat.cpp
/// SOFTWARE COMPONENT NAME           : PPort_Snsr_HeartBeat
/// GENERATED DATE                    : 2025-08-20 13:31:41
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "servicecreator/aa/port/pport_snsr_heartbeat.h"
 
namespace eevp
{
namespace simulation
{
namespace skeleton
{
 
Snsr_HeartbeatSkeletonImpl::Snsr_HeartbeatSkeletonImpl(ara::core::InstanceSpecifier instanceSpec, ara::com::MethodCallProcessingMode mode)
    : Snsr_HeartbeatSkeleton(instanceSpec, mode)
    , m_logger(ara::log::CreateLogger("SVCT", "PORT", ara::log::LogLevel::kVerbose))
{
}
 
ara::core::Future<Snsr_HeartbeatSkeleton::getHrOutput> Snsr_HeartbeatSkeletonImpl::getHr()
{
    m_logger.LogVerbose() << "PPort_Snsr_HeartBeat::getHr::Requested";
    
    getHrOutput response;
    ara::core::Promise<getHrOutput> promise;
    
    // put your logic
    
    promise.set_value(response);
    return promise.get_future();
}
 
} /// namespace skeleton
} /// namespace simulation
} /// namespace eevp

namespace servicecreator
{
namespace aa
{
namespace port
{
 
PPort_Snsr_HeartBeat::PPort_Snsr_HeartBeat()
    : m_logger(ara::log::CreateLogger("SVCT", "PORT", ara::log::LogLevel::kVerbose))
    , m_running{false}
{
}
 
PPort_Snsr_HeartBeat::~PPort_Snsr_HeartBeat()
{
}
 
void PPort_Snsr_HeartBeat::Start()
{
    m_logger.LogVerbose() << "PPort_Snsr_HeartBeat::Start";
    
    // construct skeleton
    ara::core::InstanceSpecifier specifier{"ServiceCreator/AA/PPort_Snsr_HeartBeat"};
    m_interface = std::make_unique<eevp::simulation::skeleton::Snsr_HeartbeatSkeletonImpl>(specifier);
    
    // offer service
    auto offer = m_interface->OfferService();
    if (offer.HasValue())
    {
        m_running = true;
        m_logger.LogVerbose() << "PPort_Snsr_HeartBeat::Start::OfferService";
    }
    else
    {
        m_running = false;
        m_logger.LogError() << "PPort_Snsr_HeartBeat::Start::OfferService::" << offer.Error().Message();
    }
}
 
void PPort_Snsr_HeartBeat::Terminate()
{
    m_logger.LogVerbose() << "PPort_Snsr_HeartBeat::Terminate";
    
    // stop port
    m_running = false;
    
    // stop offer service
    m_interface->StopOfferService();
    m_logger.LogVerbose() << "PPort_Snsr_HeartBeat::Terminate::StopOfferService";
}
 
} /// namespace port
} /// namespace aa
} /// namespace servicecreator
 
/// EOF