///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : pport_vcs_brakepedal.cpp
/// SOFTWARE COMPONENT NAME           : PPort_VCS_BrakePedal
/// GENERATED DATE                    : 2025-08-20 13:31:41
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "servicecreator/aa/port/pport_vcs_brakepedal.h"
 
namespace eevp
{
namespace simulation
{
namespace skeleton
{
 
VCS_BrakePedalSkeletonImpl::VCS_BrakePedalSkeletonImpl(ara::core::InstanceSpecifier instanceSpec, ara::com::MethodCallProcessingMode mode)
    : VCS_BrakePedalSkeleton(instanceSpec, mode)
    , m_logger(ara::log::CreateLogger("SVCT", "PORT", ara::log::LogLevel::kVerbose))
{
}
 
ara::core::Future<VCS_BrakePedalSkeleton::notifyBrakeStatusOutput> VCS_BrakePedalSkeletonImpl::notifyBrakeStatus()
{
    m_logger.LogVerbose() << "PPort_VCS_BrakePedal::notifyBrakeStatus::Requested";
    
    notifyBrakeStatusOutput response;
    ara::core::Promise<notifyBrakeStatusOutput> promise;
    
    // put your logic
    
    promise.set_value(response);
    return promise.get_future();
}
 
ara::core::Future<VCS_BrakePedalSkeleton::notifyBrakeSwitchOutput> VCS_BrakePedalSkeletonImpl::notifyBrakeSwitch()
{
    m_logger.LogVerbose() << "PPort_VCS_BrakePedal::notifyBrakeSwitch::Requested";
    
    notifyBrakeSwitchOutput response;
    ara::core::Promise<notifyBrakeSwitchOutput> promise;
    
    // put your logic
    
    promise.set_value(response);
    return promise.get_future();
}
 
} /// namespace skeleton
} /// namespace simulation
} /// namespace eevp

namespace servicecreator
{
namespace aa
{
namespace port
{
 
PPort_VCS_BrakePedal::PPort_VCS_BrakePedal()
    : m_logger(ara::log::CreateLogger("SVCT", "PORT", ara::log::LogLevel::kVerbose))
    , m_running{false}
{
}
 
PPort_VCS_BrakePedal::~PPort_VCS_BrakePedal()
{
}
 
void PPort_VCS_BrakePedal::Start()
{
    m_logger.LogVerbose() << "PPort_VCS_BrakePedal::Start";
    
    // construct skeleton
    ara::core::InstanceSpecifier specifier{"ServiceCreator/AA/PPort_VCS_BrakePedal"};
    m_interface = std::make_unique<eevp::simulation::skeleton::VCS_BrakePedalSkeletonImpl>(specifier);
    
    // offer service
    auto offer = m_interface->OfferService();
    if (offer.HasValue())
    {
        m_running = true;
        m_logger.LogVerbose() << "PPort_VCS_BrakePedal::Start::OfferService";
    }
    else
    {
        m_running = false;
        m_logger.LogError() << "PPort_VCS_BrakePedal::Start::OfferService::" << offer.Error().Message();
    }
}
 
void PPort_VCS_BrakePedal::Terminate()
{
    m_logger.LogVerbose() << "PPort_VCS_BrakePedal::Terminate";
    
    // stop port
    m_running = false;
    
    // stop offer service
    m_interface->StopOfferService();
    m_logger.LogVerbose() << "PPort_VCS_BrakePedal::Terminate::StopOfferService";
}
 
} /// namespace port
} /// namespace aa
} /// namespace servicecreator
 
/// EOF