///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : pport_tms_fragrance.cpp
/// SOFTWARE COMPONENT NAME           : PPort_TMS_Fragrance
/// GENERATED DATE                    : 2025-08-20 13:31:41
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "servicecreator/aa/port/pport_tms_fragrance.h"
 
namespace eevp
{
namespace simulation
{
namespace skeleton
{
 
TMS_FragranceSkeletonImpl::TMS_FragranceSkeletonImpl(ara::core::InstanceSpecifier instanceSpec, ara::com::MethodCallProcessingMode mode)
    : TMS_FragranceSkeleton(instanceSpec, mode)
    , m_logger(ara::log::CreateLogger("SVCT", "PORT", ara::log::LogLevel::kVerbose))
{
}
 
ara::core::Future<TMS_FragranceSkeleton::getConcentrationOutput> TMS_FragranceSkeletonImpl::getConcentration()
{
    m_logger.LogVerbose() << "PPort_TMS_Fragrance::getConcentration::Requested";
    
    getConcentrationOutput response;
    ara::core::Promise<getConcentrationOutput> promise;
    
    // put your logic
    
    promise.set_value(response);
    return promise.get_future();
}
 
ara::core::Future<TMS_FragranceSkeleton::getTypeOutput> TMS_FragranceSkeletonImpl::getType()
{
    m_logger.LogVerbose() << "PPort_TMS_Fragrance::getType::Requested";
    
    getTypeOutput response;
    ara::core::Promise<getTypeOutput> promise;
    
    // put your logic
    
    promise.set_value(response);
    return promise.get_future();
}
 
ara::core::Future<TMS_FragranceSkeleton::isRunningOutput> TMS_FragranceSkeletonImpl::isRunning()
{
    m_logger.LogVerbose() << "PPort_TMS_Fragrance::isRunning::Requested";
    
    isRunningOutput response;
    ara::core::Promise<isRunningOutput> promise;
    
    // put your logic
    
    promise.set_value(response);
    return promise.get_future();
}
 
ara::core::Future<TMS_FragranceSkeleton::setConcentrationOutput> TMS_FragranceSkeletonImpl::setConcentration(const std::uint16_t& concentration)
{
    m_logger.LogVerbose() << "PPort_TMS_Fragrance::setConcentration::Requested";
    
    setConcentrationOutput response;
    ara::core::Promise<setConcentrationOutput> promise;
    
    // put your logic
    
    promise.set_value(response);
    return promise.get_future();
}
 
ara::core::Future<TMS_FragranceSkeleton::setTypeOutput> TMS_FragranceSkeletonImpl::setType(const eevp::simulation::type::TMS_FragranceType& type)
{
    m_logger.LogVerbose() << "PPort_TMS_Fragrance::setType::Requested";
    
    setTypeOutput response;
    ara::core::Promise<setTypeOutput> promise;
    
    // put your logic
    
    promise.set_value(response);
    return promise.get_future();
}
 
ara::core::Future<TMS_FragranceSkeleton::turnOffOutput> TMS_FragranceSkeletonImpl::turnOff()
{
    m_logger.LogVerbose() << "PPort_TMS_Fragrance::turnOff::Requested";
    
    turnOffOutput response;
    ara::core::Promise<turnOffOutput> promise;
    
    // put your logic
    
    promise.set_value(response);
    return promise.get_future();
}
 
ara::core::Future<TMS_FragranceSkeleton::turnOnOutput> TMS_FragranceSkeletonImpl::turnOn()
{
    m_logger.LogVerbose() << "PPort_TMS_Fragrance::turnOn::Requested";
    
    turnOnOutput response;
    ara::core::Promise<turnOnOutput> promise;
    
    // put your logic
    
    promise.set_value(response);
    return promise.get_future();
}
 
} /// namespace skeleton
} /// namespace simulation
} /// namespace eevp

namespace servicecreator
{
namespace aa
{
namespace port
{
 
PPort_TMS_Fragrance::PPort_TMS_Fragrance()
    : m_logger(ara::log::CreateLogger("SVCT", "PORT", ara::log::LogLevel::kVerbose))
    , m_running{false}
{
}
 
PPort_TMS_Fragrance::~PPort_TMS_Fragrance()
{
}
 
void PPort_TMS_Fragrance::Start()
{
    m_logger.LogVerbose() << "PPort_TMS_Fragrance::Start";
    
    // construct skeleton
    ara::core::InstanceSpecifier specifier{"ServiceCreator/AA/PPort_TMS_Fragrance"};
    m_interface = std::make_unique<eevp::simulation::skeleton::TMS_FragranceSkeletonImpl>(specifier);
    
    // offer service
    auto offer = m_interface->OfferService();
    if (offer.HasValue())
    {
        m_running = true;
        m_logger.LogVerbose() << "PPort_TMS_Fragrance::Start::OfferService";
    }
    else
    {
        m_running = false;
        m_logger.LogError() << "PPort_TMS_Fragrance::Start::OfferService::" << offer.Error().Message();
    }
}
 
void PPort_TMS_Fragrance::Terminate()
{
    m_logger.LogVerbose() << "PPort_TMS_Fragrance::Terminate";
    
    // stop port
    m_running = false;
    
    // stop offer service
    m_interface->StopOfferService();
    m_logger.LogVerbose() << "PPort_TMS_Fragrance::Terminate::StopOfferService";
}
 
} /// namespace port
} /// namespace aa
} /// namespace servicecreator
 
/// EOF