///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : pport_vcs_brake.cpp
/// SOFTWARE COMPONENT NAME           : PPort_VCS_Brake
/// GENERATED DATE                    : 2025-08-20 13:31:41
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "servicecreator/aa/port/pport_vcs_brake.h"
 
namespace eevp
{
namespace simulation
{
namespace skeleton
{
 
VCS_BrakeSkeletonImpl::VCS_BrakeSkeletonImpl(ara::core::InstanceSpecifier instanceSpec, ara::com::MethodCallProcessingMode mode)
    : VCS_BrakeSkeleton(instanceSpec, mode)
    , m_logger(ara::log::CreateLogger("SVCT", "PORT", ara::log::LogLevel::kVerbose))
{
}
 
ara::core::Future<VCS_BrakeSkeleton::notifyMCPrsOutput> VCS_BrakeSkeletonImpl::notifyMCPrs()
{
    m_logger.LogVerbose() << "PPort_VCS_Brake::notifyMCPrs::Requested";
    
    notifyMCPrsOutput response;
    ara::core::Promise<notifyMCPrsOutput> promise;
    
    // put your logic
    
    promise.set_value(response);
    return promise.get_future();
}
 
ara::core::Future<VCS_BrakeSkeleton::notifyTqOutput> VCS_BrakeSkeletonImpl::notifyTq()
{
    m_logger.LogVerbose() << "PPort_VCS_Brake::notifyTq::Requested";
    
    notifyTqOutput response;
    ara::core::Promise<notifyTqOutput> promise;
    
    // put your logic
    
    promise.set_value(response);
    return promise.get_future();
}
 
ara::core::Future<VCS_BrakeSkeleton::setTargetAxOutput> VCS_BrakeSkeletonImpl::setTargetAx(const eevp::simulation::type::VCS_Acceleration& ax)
{
    m_logger.LogVerbose() << "PPort_VCS_Brake::setTargetAx::Requested";
    
    setTargetAxOutput response;
    ara::core::Promise<setTargetAxOutput> promise;
    
    // put your logic
    
    promise.set_value(response);
    return promise.get_future();
}
 
ara::core::Future<VCS_BrakeSkeleton::setTotalForceOutput> VCS_BrakeSkeletonImpl::setTotalForce(const eevp::simulation::type::VCS_LgtBrkFTotal& lgtBrkFTotal)
{
    m_logger.LogVerbose() << "PPort_VCS_Brake::setTotalForce::Requested";
    
    setTotalForceOutput response;
    ara::core::Promise<setTotalForceOutput> promise;
    
    // put your logic
    
    promise.set_value(response);
    return promise.get_future();
}
 
} /// namespace skeleton
} /// namespace simulation
} /// namespace eevp

namespace servicecreator
{
namespace aa
{
namespace port
{
 
PPort_VCS_Brake::PPort_VCS_Brake()
    : m_logger(ara::log::CreateLogger("SVCT", "PORT", ara::log::LogLevel::kVerbose))
    , m_running{false}
{
}
 
PPort_VCS_Brake::~PPort_VCS_Brake()
{
}
 
void PPort_VCS_Brake::Start()
{
    m_logger.LogVerbose() << "PPort_VCS_Brake::Start";
    
    // construct skeleton
    ara::core::InstanceSpecifier specifier{"ServiceCreator/AA/PPort_VCS_Brake"};
    m_interface = std::make_unique<eevp::simulation::skeleton::VCS_BrakeSkeletonImpl>(specifier);
    
    // offer service
    auto offer = m_interface->OfferService();
    if (offer.HasValue())
    {
        m_running = true;
        m_logger.LogVerbose() << "PPort_VCS_Brake::Start::OfferService";
    }
    else
    {
        m_running = false;
        m_logger.LogError() << "PPort_VCS_Brake::Start::OfferService::" << offer.Error().Message();
    }
}
 
void PPort_VCS_Brake::Terminate()
{
    m_logger.LogVerbose() << "PPort_VCS_Brake::Terminate";
    
    // stop port
    m_running = false;
    
    // stop offer service
    m_interface->StopOfferService();
    m_logger.LogVerbose() << "PPort_VCS_Brake::Terminate::StopOfferService";
}
 
} /// namespace port
} /// namespace aa
} /// namespace servicecreator
 
/// EOF