///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : rportgear.h
/// SOFTWARE COMPONENT NAME           : RPortGear
/// GENERATED DATE                    : 2025-08-30 13:10:16
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_AA_GEN_SOFTWARE_COMPONENT_RPORT_PREVENTROLLBACK_AA_RPORTGEAR_H
#define PARA_AA_GEN_SOFTWARE_COMPONENT_RPORT_PREVENTROLLBACK_AA_RPORTGEAR_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "eevp/simulation/vcs_gear_proxy.h"
 
#include "ara/log/logger.h"
 
#include <mutex>
#include <thread>
 
namespace preventrollback
{
namespace aa
{
namespace port
{
 
class RPortGear
{
public:
    /// @brief Constructor
    RPortGear();
    
    /// @brief Destructor
    ~RPortGear();
    
    /// @brief Start port
    void Start();
    
    /// @brief Terminate port
    void Terminate();

    /// @brief Request with Response method using by software component, notifyGear
    void RequestnotifyGear();
     
    /// @brief Regist callback from software component
    void RegistResponseHandlernotifyGear(std::function<void(const eevp::simulation::proxy::methods::notifyGear::Output&)> handler);
    
    /// @brief Request with Response method using by software component, setTarget
    void RequestsetTarget(const eevp::simulation::type::VCS_Gear& targetGear);
     
    /// @brief Regist callback from software component
    void RegistResponseHandlersetTarget(std::function<void(const eevp::simulation::proxy::methods::setTarget::Output&)> handler);
    
private:
    /// @brief Callback for find service
    void Find(ara::com::ServiceHandleContainer<eevp::simulation::proxy::VCS_GearProxy::HandleType> handles,
              ara::com::FindServiceHandle findHandle);

private:
    /// @brief Logger for this port
    ara::log::Logger& m_logger;
    
    /// @brief Flag of port status
    bool m_running;
    
    /// @brief Flag of find service status
    bool m_found;
    
    /// @brief Mutex for this port
    std::mutex m_mutex; 
    
    /// @brief AUTOSAR Port Interface
    std::unique_ptr<eevp::simulation::proxy::VCS_GearProxy> m_interface;
    
    /// @brief Find service handle
    std::unique_ptr<ara::com::FindServiceHandle> m_findHandle;

    /// @brief Callback from software component, notifyGear
    std::function<void(const eevp::simulation::proxy::methods::notifyGear::Output&)> m_respondernotifyGear;
    
    /// @brief Callback from software component, setTarget
    std::function<void(const eevp::simulation::proxy::methods::setTarget::Output&)> m_respondersetTarget;
};
 
} /// namespace port
} /// namespace aa
} /// namespace preventrollback
 
#endif /// PARA_AA_GEN_SOFTWARE_COMPONENT_RPORT_PREVENTROLLBACK_AA_RPORTGEAR_H