///////////////////////////////////////////////////////////////////////////////////////////////////////////
///
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.
///
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : intelligentwiper.h
/// SOFTWARE COMPONENT NAME           : IntelligentWiper
/// GENERATED DATE                    : 2025-08-14 16:16:30
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_AA_GEN_SOFTWARE_COMPONENT_INTELLIGENTWIPER_AA_H
#define PARA_AA_GEN_SOFTWARE_COMPONENT_INTELLIGENTWIPER_AA_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "intelligentwiper/aa/port/rport_wiper.h"
#include "intelligentwiper/aa/port/rport_vehicleinfo.h"
#include "intelligentwiper/aa/port/rport_subscriptionmanagement.h"
#include "intelligentwiper/aa/port/rport_pdw_front.h"
#include "intelligentwiper/aa/port/rport_pdw_rear.h"

#include "para/swc/port_pool.h"

#include <memory>
#include <thread>
#include <chrono>

#include "logic.h" // Logic 클래스 헤더 포함

namespace intelligentwiper
{
    namespace aa
    {

        class IntelligentWiper
        {
        public:
            /// @brief Constructor
            IntelligentWiper();

            /// @brief Destructor
            ~IntelligentWiper();

            /// @brief Initialize software component
            bool Initialize();

            /// @brief Start software component
            void Start();

            /// @brief Terminate software component
            void Terminate();

            /// @brief Run software component
            void Run();

        private:
            /// @brief Running status of software component
            bool m_running;

            /// @brief Pool of port
            ::para::swc::PortPool m_workers;

            /// @brief Logger for software component
            ara::log::Logger &m_logger;

            /// @brief Logic instance
            std::unique_ptr<intelligentwiper::aa::Logic> m_logic;

            /// @brief Instance of Port {IntelligentWiper.RPort_Wiper}
            std::unique_ptr<intelligentwiper::aa::port::RPort_Wiper> m_RPort_Wiper;

            /// @brief Instance of Port {IntelligentWiper.RPort_VehicleInfo}
            std::unique_ptr<intelligentwiper::aa::port::RPort_VehicleInfo> m_RPort_VehicleInfo;

            /// @brief Instance of Port {IntelligentWiper.RPort_SubscriptionManagement}
            std::unique_ptr<intelligentwiper::aa::port::RPort_SubscriptionManagement> m_RPort_SubscriptionManagement;

            /// @brief Instance of Port {IntelligentWiper.RPort_PDW_FRONT}
            std::unique_ptr<intelligentwiper::aa::port::RPort_PDW_FRONT> m_RPort_PDW_FRONT;

            /// @brief Instance of Port {IntelligentWiper.RPort_PDW_REAR}
            std::unique_ptr<intelligentwiper::aa::port::RPort_PDW_REAR> m_RPort_PDW_REAR;

            /// @brief Logic thread
            std::thread m_logicThread;
        };

    } /// namespace aa
} /// namespace intelligentwiper

#endif /// PARA_AA_GEN_SOFTWARE_COMPONENT_INTELLIGENTWIPER_AA_H