///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : rportvcs_brakepedal.cpp
/// SOFTWARE COMPONENT NAME           : RPortVCS_BrakePedal
/// GENERATED DATE                    : 2025-08-30 10:53:29
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "preventrollback/aa/port/rportvcs_brakepedal.h"
 
namespace preventrollback
{
namespace aa
{
namespace port
{
 
RPortVCS_BrakePedal::RPortVCS_BrakePedal()
    : m_logger(ara::log::CreateLogger("PRRB", "PORT", ara::log::LogLevel::kVerbose))
    , m_running{false}
    , m_found{false}
    , m_respondernotifyBrakeStatus{nullptr}
    , m_respondernotifyBrakeSwitch{nullptr}
{
}
 
RPortVCS_BrakePedal::~RPortVCS_BrakePedal()
{
}
 
void RPortVCS_BrakePedal::Start()
{
    m_logger.LogVerbose() << "RPortVCS_BrakePedal::Start";
    
    // regist callback
    ara::core::InstanceSpecifier specifier{"PreventRollback/AA/RPortVCS_BrakePedal"};
    auto handler = [this](ara::com::ServiceHandleContainer<eevp::simulation::proxy::VCS_BrakePedalProxy::HandleType> handles,
                          ara::com::FindServiceHandle findHandle) {
        this->Find(handles, findHandle);
    };
    
    // find service
    auto find = eevp::simulation::proxy::VCS_BrakePedalProxy::StartFindService(handler, specifier);
    if (find.HasValue())
    {
        m_logger.LogVerbose() << "RPortVCS_BrakePedal::Start::StartFindService";
    }
    else
    {
        m_logger.LogError() << "RPortVCS_BrakePedal::Start::StartFindService::" << find.Error().Message();
    }
    
    // run port
    m_running = true;
}
 
void RPortVCS_BrakePedal::Terminate()
{
    m_logger.LogVerbose() << "RPortVCS_BrakePedal::Terminate";
    
    // stop port
    m_running = false;
    
    // clear service proxy
    if (m_interface)
    {
        
        // stop find service
        m_interface->StopFindService(*m_findHandle);
        m_found = false;
        
        m_logger.LogVerbose() << "RPortVCS_BrakePedal::Terminate::StopFindService";
    }
}
 
void RPortVCS_BrakePedal::Find(ara::com::ServiceHandleContainer<eevp::simulation::proxy::VCS_BrakePedalProxy::HandleType> handles, ara::com::FindServiceHandle findHandle)
{
    // check finding handles
    if (handles.empty())
    {
        m_logger.LogVerbose() << "RPortVCS_BrakePedal::Find::Service Instances not found";
        return;
    }
    else
    {
        for (auto& handle : handles)
        {
            m_logger.LogVerbose() << "RPortVCS_BrakePedal::Find::Searched Instance::ServiceId =" << 
                                     handle.GetServiceHandle().serviceId << 
                                     ", InstanceId =" << 
                                     handle.GetServiceHandle().instanceId;
        }
    }
    
    // create proxy
    if (m_interface)
    {
        m_logger.LogVerbose() << "RPortVCS_BrakePedal::Find::Proxy is already running";
    }
    else
    {
        m_logger.LogVerbose() << "RPortVCS_BrakePedal::Find::Using Instance::ServiceId =" << 
                                 handles[0].GetServiceHandle().serviceId << 
                                 ", InstanceId =" << 
                                 handles[0].GetServiceHandle().instanceId;
        m_interface = std::make_unique<eevp::simulation::proxy::VCS_BrakePedalProxy>(handles[0]);
        m_findHandle = std::make_unique<ara::com::FindServiceHandle>(findHandle);
        m_found = true;
        
    }
}
 
void RPortVCS_BrakePedal::RequestnotifyBrakeStatus()
{
    if (m_found)
    {
        auto request = m_interface->notifyBrakeStatus();
        request.wait();
        auto response = request.GetResult();
        if (response.HasValue())
        {
            m_logger.LogVerbose() << "RPortVCS_BrakePedal::RequestnotifyBrakeStatus::Responded";
            
            auto result = response.Value();
            if (m_respondernotifyBrakeStatus)
            {
                m_respondernotifyBrakeStatus(result);
            }
        }
        else
        {
            m_logger.LogError() << "RPortVCS_BrakePedal::RequestnotifyBrakeStatus::" << response.Error().Message();
        }
    }
}
 
void RPortVCS_BrakePedal::RegistResponseHandlernotifyBrakeStatus(std::function<void(const eevp::simulation::proxy::methods::notifyBrakeStatus::Output&)> handler)
{
    m_respondernotifyBrakeStatus = handler;
}
 
void RPortVCS_BrakePedal::RequestnotifyBrakeSwitch()
{
    if (m_found)
    {
        auto request = m_interface->notifyBrakeSwitch();
        request.wait();
        auto response = request.GetResult();
        if (response.HasValue())
        {
            m_logger.LogVerbose() << "RPortVCS_BrakePedal::RequestnotifyBrakeSwitch::Responded";
            
            auto result = response.Value();
            if (m_respondernotifyBrakeSwitch)
            {
                m_respondernotifyBrakeSwitch(result);
            }
        }
        else
        {
            m_logger.LogError() << "RPortVCS_BrakePedal::RequestnotifyBrakeSwitch::" << response.Error().Message();
        }
    }
}
 
void RPortVCS_BrakePedal::RegistResponseHandlernotifyBrakeSwitch(std::function<void(const eevp::simulation::proxy::methods::notifyBrakeSwitch::Output&)> handler)
{
    m_respondernotifyBrakeSwitch = handler;
}
 
} /// namespace port
} /// namespace aa
} /// namespace preventrollback
 
/// EOF