///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : rportaccrpedal.cpp
/// SOFTWARE COMPONENT NAME           : RPortAccrPedal
/// GENERATED DATE                    : 2025-08-30 13:10:17
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "preventrollback/aa/port/rportaccrpedal.h"
 
namespace preventrollback
{
namespace aa
{
namespace port
{
 
RPortAccrPedal::RPortAccrPedal()
    : m_logger(ara::log::CreateLogger("PRRB", "PORT", ara::log::LogLevel::kVerbose))
    , m_running{false}
    , m_found{false}
    , m_respondernotifyAccrPedal{nullptr}
{
}
 
RPortAccrPedal::~RPortAccrPedal()
{
}
 
void RPortAccrPedal::Start()
{
    m_logger.LogVerbose() << "RPortAccrPedal::Start";
    
    // regist callback
    ara::core::InstanceSpecifier specifier{"PreventRollback/AA/RPortAccrPedal"};
    auto handler = [this](ara::com::ServiceHandleContainer<eevp::simulation::proxy::VCS_AccrPedalProxy::HandleType> handles,
                          ara::com::FindServiceHandle findHandle) {
        this->Find(handles, findHandle);
    };
    
    // find service
    auto find = eevp::simulation::proxy::VCS_AccrPedalProxy::StartFindService(handler, specifier);
    if (find.HasValue())
    {
        m_logger.LogVerbose() << "RPortAccrPedal::Start::StartFindService";
    }
    else
    {
        m_logger.LogError() << "RPortAccrPedal::Start::StartFindService::" << find.Error().Message();
    }
    
    // run port
    m_running = true;
}
 
void RPortAccrPedal::Terminate()
{
    m_logger.LogVerbose() << "RPortAccrPedal::Terminate";
    
    // stop port
    m_running = false;
    
    // clear service proxy
    if (m_interface)
    {
        
        // stop find service
        m_interface->StopFindService(*m_findHandle);
        m_found = false;
        
        m_logger.LogVerbose() << "RPortAccrPedal::Terminate::StopFindService";
    }
}
 
void RPortAccrPedal::Find(ara::com::ServiceHandleContainer<eevp::simulation::proxy::VCS_AccrPedalProxy::HandleType> handles, ara::com::FindServiceHandle findHandle)
{
    // check finding handles
    if (handles.empty())
    {
        m_logger.LogVerbose() << "RPortAccrPedal::Find::Service Instances not found";
        return;
    }
    else
    {
        for (auto& handle : handles)
        {
            m_logger.LogVerbose() << "RPortAccrPedal::Find::Searched Instance::ServiceId =" << 
                                     handle.GetServiceHandle().serviceId << 
                                     ", InstanceId =" << 
                                     handle.GetServiceHandle().instanceId;
        }
    }
    
    // create proxy
    if (m_interface)
    {
        m_logger.LogVerbose() << "RPortAccrPedal::Find::Proxy is already running";
    }
    else
    {
        m_logger.LogVerbose() << "RPortAccrPedal::Find::Using Instance::ServiceId =" << 
                                 handles[0].GetServiceHandle().serviceId << 
                                 ", InstanceId =" << 
                                 handles[0].GetServiceHandle().instanceId;
        m_interface = std::make_unique<eevp::simulation::proxy::VCS_AccrPedalProxy>(handles[0]);
        m_findHandle = std::make_unique<ara::com::FindServiceHandle>(findHandle);
        m_found = true;
        
    }
}
 
void RPortAccrPedal::RequestnotifyAccrPedal()
{
    if (m_found)
    {
        auto request = m_interface->notifyAccrPedal();
        request.wait();
        auto response = request.GetResult();
        if (response.HasValue())
        {
            m_logger.LogVerbose() << "RPortAccrPedal::RequestnotifyAccrPedal::Responded";
            
            auto result = response.Value();
            if (m_respondernotifyAccrPedal)
            {
                m_respondernotifyAccrPedal(result);
            }
        }
        else
        {
            m_logger.LogError() << "RPortAccrPedal::RequestnotifyAccrPedal::" << response.Error().Message();
        }
    }
}
 
void RPortAccrPedal::RegistResponseHandlernotifyAccrPedal(std::function<void(const eevp::simulation::proxy::methods::notifyAccrPedal::Output&)> handler)
{
    m_respondernotifyAccrPedal = handler;
}
 
} /// namespace port
} /// namespace aa
} /// namespace preventrollback
 
/// EOF