///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : rportgear.cpp
/// SOFTWARE COMPONENT NAME           : RPortGear
/// GENERATED DATE                    : 2025-08-30 13:10:18
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "preventrollback/aa/port/rportgear.h"
 
namespace preventrollback
{
namespace aa
{
namespace port
{
 
RPortGear::RPortGear()
    : m_logger(ara::log::CreateLogger("PRRB", "PORT", ara::log::LogLevel::kVerbose))
    , m_running{false}
    , m_found{false}
    , m_respondernotifyGear{nullptr}
    , m_respondersetTarget{nullptr}
{
}
 
RPortGear::~RPortGear()
{
}
 
void RPortGear::Start()
{
    m_logger.LogVerbose() << "RPortGear::Start";
    
    // regist callback
    ara::core::InstanceSpecifier specifier{"PreventRollback/AA/RPortGear"};
    auto handler = [this](ara::com::ServiceHandleContainer<eevp::simulation::proxy::VCS_GearProxy::HandleType> handles,
                          ara::com::FindServiceHandle findHandle) {
        this->Find(handles, findHandle);
    };
    
    // find service
    auto find = eevp::simulation::proxy::VCS_GearProxy::StartFindService(handler, specifier);
    if (find.HasValue())
    {
        m_logger.LogVerbose() << "RPortGear::Start::StartFindService";
    }
    else
    {
        m_logger.LogError() << "RPortGear::Start::StartFindService::" << find.Error().Message();
    }
    
    // run port
    m_running = true;
}
 
void RPortGear::Terminate()
{
    m_logger.LogVerbose() << "RPortGear::Terminate";
    
    // stop port
    m_running = false;
    
    // clear service proxy
    if (m_interface)
    {
        
        // stop find service
        m_interface->StopFindService(*m_findHandle);
        m_found = false;
        
        m_logger.LogVerbose() << "RPortGear::Terminate::StopFindService";
    }
}
 
void RPortGear::Find(ara::com::ServiceHandleContainer<eevp::simulation::proxy::VCS_GearProxy::HandleType> handles, ara::com::FindServiceHandle findHandle)
{
    // check finding handles
    if (handles.empty())
    {
        m_logger.LogVerbose() << "RPortGear::Find::Service Instances not found";
        return;
    }
    else
    {
        for (auto& handle : handles)
        {
            m_logger.LogVerbose() << "RPortGear::Find::Searched Instance::ServiceId =" << 
                                     handle.GetServiceHandle().serviceId << 
                                     ", InstanceId =" << 
                                     handle.GetServiceHandle().instanceId;
        }
    }
    
    // create proxy
    if (m_interface)
    {
        m_logger.LogVerbose() << "RPortGear::Find::Proxy is already running";
    }
    else
    {
        m_logger.LogVerbose() << "RPortGear::Find::Using Instance::ServiceId =" << 
                                 handles[0].GetServiceHandle().serviceId << 
                                 ", InstanceId =" << 
                                 handles[0].GetServiceHandle().instanceId;
        m_interface = std::make_unique<eevp::simulation::proxy::VCS_GearProxy>(handles[0]);
        m_findHandle = std::make_unique<ara::com::FindServiceHandle>(findHandle);
        m_found = true;
        
    }
}
 
void RPortGear::RequestnotifyGear()
{
    if (m_found)
    {
        auto request = m_interface->notifyGear();
        request.wait();
        auto response = request.GetResult();
        if (response.HasValue())
        {
            m_logger.LogVerbose() << "RPortGear::RequestnotifyGear::Responded";
            
            auto result = response.Value();
            if (m_respondernotifyGear)
            {
                m_respondernotifyGear(result);
            }
        }
        else
        {
            m_logger.LogError() << "RPortGear::RequestnotifyGear::" << response.Error().Message();
        }
    }
}
 
void RPortGear::RegistResponseHandlernotifyGear(std::function<void(const eevp::simulation::proxy::methods::notifyGear::Output&)> handler)
{
    m_respondernotifyGear = handler;
}
 
void RPortGear::RequestsetTarget(const eevp::simulation::type::VCS_Gear& targetGear)
{
    if (m_found)
    {
        auto request = m_interface->setTarget(targetGear);
        request.wait();
        auto response = request.GetResult();
        if (response.HasValue())
        {
            m_logger.LogVerbose() << "RPortGear::RequestsetTarget::Responded";
            
            auto result = response.Value();
            if (m_respondersetTarget)
            {
                m_respondersetTarget(result);
            }
        }
        else
        {
            m_logger.LogError() << "RPortGear::RequestsetTarget::" << response.Error().Message();
        }
    }
}
 
void RPortGear::RegistResponseHandlersetTarget(std::function<void(const eevp::simulation::proxy::methods::setTarget::Output&)> handler)
{
    m_respondersetTarget = handler;
}
 
} /// namespace port
} /// namespace aa
} /// namespace preventrollback
 
/// EOF